### PR TITLE
Check common.licenseInformation, common.tier, common.automaticUpgrade

### PR DESCRIPTION
**Pull request by klein0r**
* Added check for licenseInformation
* Added check for required attribute common.tier
* Added check for required attribute common.automaticUpgrade

### CODE REVIEW

**Comment by mcm1957** [comment]
Line 2021 (https://github.com/ioBroker/ioBroker.repochecker/blob/d24e78d6a3ff0fe208d00265280c4438a0b14ab9/index.js#L2021)
seems to be corrupt:

``` let repoUrl = 'https://github.com/klein0r/ioBroker.luftdaten';```


Repo Checker MIUST not check anything not yet provided by adapter creator - at least not at level ERROR.

**Comment by mcm1957** [comment]
Additional question:
Where are the new attributes documented ?
How is it planned to inform developers ?

**Comment by klein0r** [comment]
> Where are the new attributes documented ?

Just in the schema - so your IDE should help you to remove those warnings:

- https://github.com/ioBroker/ioBroker.js-controller/blob/c45cf0b5150f4268f4250635490d330a8caab541/schemas/io-package.json#L833-L879
- https://github.com/ioBroker/ioBroker.js-controller/blob/c45cf0b5150f4268f4250635490d330a8caab541/schemas/io-package.json#L776-L785

> Repo Checker MIUST not check anything not yet provided by adapter creator

Okay, but those attributes (like `licenseInformation`) are marked as required in the official schema. So my IDE complains about missing `tier` or `licenseInformation`.

**Comment by klein0r** [comment]
licenseInformation is already included in create-adapter: https://github.com/ioBroker/create-adapter/pull/1092

**Comment by Apollon77** [comment]
mybwe lets use warnings for now? in fact repo is built in a backward compatible way

**Comment by klein0r** [comment]
I've just updated the existing error message for the new attribute (which was also an error):

https://github.com/ioBroker/ioBroker.repochecker/blob/e81d359e0f245503d66cd2787d6428cb29fd9df6/index.js#L874-L876

**Comment by klein0r** [comment]
> What about [common.automaticUpgrade] ?

See PR. It's a js-controller 5.1 feature and just validated. There is no error or warning if nothing is defined.

**Comment by Apollon77** [comment]
@klein0r We discussed today in Dev Meeting: automaticUpgrade should be validated as "not included" from developer side. This field is just set by the User via Admin ... So yes it is formally part of the schema, but irrelevant for the developer.

Default tier schould be 2 in my eyes

**Pull request merged**
